export const CONSTRUCTION_STATUS = {
  PENDING: 'PENDING',
  IN_PROGRESS: 'IN_PROGRESS',
  COMPLETED: 'COMPLETED',
  CANCELLED: 'CANCELLED'
}

export const CONSTRUCTION_STATUS_LABELS = {
  [CONSTRUCTION_STATUS.PENDING]: 'Chờ duyệt',
  [CONSTRUCTION_STATUS.IN_PROGRESS]: 'Đang thi công',
  [CONSTRUCTION_STATUS.COMPLETED]: 'Hoàn thành',
  [CONSTRUCTION_STATUS.CANCELLED]: 'Đã hủy'
}

export const CONSTRUCTION_STATUS_COLORS = {
  [CONSTRUCTION_STATUS.PENDING]: 'warning',
  [CONSTRUCTION_STATUS.IN_PROGRESS]: 'info',
  [CONSTRUCTION_STATUS.COMPLETED]: 'success',
  [CONSTRUCTION_STATUS.CANCELLED]: 'danger'
}
